# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hoping Tang Blog
email: wan52390010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Hoping Tang's Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hopingtang.github.io/" # the base hostname & protocol for your site
twitter_username: Hoping_Tang
github_username:  Hoping

# Build settings
markdown: redcarpet
